name: goreleaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      -
        name: Go Mod
        run: |
          go mod tidy
          go mod download
      -
        name: Go Testing
        run: |
          go test -v ./...
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release ${{ startsWith(github.ref, 'refs/tags/') && '--clean' || '--clean --snapshot' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: |
            dist/*/go-apt-cacher
            dist/*/go-apt-mirror
